
# Course information

course: ""
term: ""


# Authentication credentials and tokens

csstaff:
  username: ""
  password: ""

codePost:
  api_key: ""

ed:
  username: ""
  password: ""

gradescope:
  username: ""
  password: ""

tigerfile:
  token: ""

labqueue:
  username: ""
  password: ""

canvas:
  token: ""


# Mappings between the names of various services that this library is integrating

#normalizations:
#  - source: runscript
#    destination: tigerfile
#    mapping:
#      hello: Hello
#      loops: Loops
#      nbody: NBody
#      sierpinski: Sierpinski
#      hamming: Hamming
#      lfsr: LFSR
#      guitar: Guitar
#      markov: Markov
#      tsp: TSP
#      atomic: Atomic
#  - source: tigerfile
#    destination: codepost
#    mapping:
#      Hello: Hello
#      Loops: Loops
#      NBody: NBody
#      Sierpinski: Sierpinski
#      Hamming: Hamming
#      LFSR: LFSR
#      Guitar: Guitar
#      Markov: Markov
#      TSP: "Traveling Salesperson Problem"
#      Atomic: Atomic


# Course policy constants

policy:
  cutoffs:
    "A" : 93
    "A-": 90
    "B+": 87
    "B" : 83
    "B-": 80
    "C+": 77
    "C" : 73
    "C-": 70
    "D" : 60
    "F" : 0

  lateness:
    allotted: 4
    penalty: 0.5
    grace_minutes: 180

#  totals:
#    Hello: 4.0
#    Loops: 4.0
#    NBody: 4.0
#    Sierpinski: 4.0
#    Hamming: 4.0
#    Programming Exam 1: 7.5
#    Written Exam 1: 17.5
#    LFSR: 5.0,
#    Guitar: 5.0,
#    Markov: 5.0,
#    TSPP: 5.0,
#    Programming Exam 2: 7.5
#    Written Exam 2: 17.5
#    Atomic: 10.0