course: ""
term: ""

csstaff:
  username: ""
  password: ""

codePost:
  api_key: ""

ed:
  username: ""
  password: ""

gradescope:
  username: ""
  password: ""

tigerfile:
  token: ""

labqueue:
  username: ""
  password: ""
